spring.application.name = MediGo
server.port = ${PORT}

spring.datasource.url= ${SPRING_DATASOURCE_URL}

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.datasource.username = ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password = ${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#it will automatically create table via hibernate
spring.jpa.hibernate.ddl-auto = update

#validate -> if we write validate in above line then it will not create table automatically.

#defining each file size the backend can accept
spring.servlet.multipart.max-file-size = 2MB 

#defining total file size the backend can accept 
spring.servlet.multipart.max-request-size = 20MB 
spring.jpa.show-sql = false
cohere.api.key = ${COHERE_API_KEY}
app.base-url=${APP_BASE_URL}
