spring.application.name=MediGo
server.port=9090

spring.datasource.url = jdbc:mysql://localhost:3306/medigo_db

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

spring.datasource.username = root
spring.datasource.password = root

#it will automatically create table via hibernate
spring.jpa.hibernate.ddl-auto = update

#validate -> if we write validate in above line then it will not create table automatically.

#defining each file size the backend can accept
spring.servlet.multipart.max-file-size = 2MB 

#defining total file size the backend can accept 
spring.servlet.multipart.max-request-size = 20MB 
spring.jpa.show-sql=true
cohere.api.key=${COHERE_API_KEY}